# Generated by Django 4.1.4 on 2023-02-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='location',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
