# Generated by Django 4.1.4 on 2023-02-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
