# Generated by Django 4.1.4 on 2023-02-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='eta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('ACCEPTED', 'ACCEPTED'), ('DECLINED', 'DECLINED'), ('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING')], default='NEW', max_length=20),
        ),
    ]
