# Generated by Django 4.1.4 on 2023-02-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_eta_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
