# Generated by Django 4.1.4 on 2023-02-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orders_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='location',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='orders',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='u_phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='orders',
            name='v_phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
