# Generated by Django 4.1.4 on 2023-02-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_vehicle_models_vehicle_alter_orders_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
