# Generated by Django 4.1.4 on 2023-02-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orders_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='my_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='my_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
