# Generated by Django 4.1.4 on 2023-02-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orders_my_date_orders_my_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='service',
            field=models.CharField(blank=True, choices=[('ROAD', 'ROAD'), ('HOME', 'HOME')], max_length=10),
        ),
    ]
