# Generated by Django 4.1.4 on 2023-02-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orders_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='my_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='my_time',
            new_name='time',
        ),
    ]
